version: '3'

services:

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"

  redis:
    image: redis:4.0.10
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.7.6-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"

  auth:
    build: ../vendor/authorizer
    ports:
      - "8005:8005"

  gateway:
    image: quay.io/datawire/ambassador:0.40.0
    ports:
      - "8080:80"
    depends_on:
      - auth
    volumes:
      - ./gateway:/ambassador/ambassador-config/:ro
    entrypoint:
      - sh
      - -exc
      - |
        # Allow accessing host's 0.0.0.0 so we can connect to a local peatio
        # from the gateway container
        ip -4 route list match 0/0 | awk '{print $$3" peatio.local"}' >> /etc/hosts
        # Continue with the default entrypoint
        ./entrypoint.sh

volumes:
  db_data:
  rabbitmq_data:
  redis_data:
